<?php include_once 'header.php';?>
<div class="border marTop-1px pad30px">
	<p><strong>Terms of Use and License Agreement for SimpleTruckTax Software and Services</strong></p>
	<p class="marTop10px"><strong>Terms</strong></p>
	<p class="marTop10px">
		Thank you for selecting SimpleTruckTax, tax preparation software. This license agreement ("Agreement") gives you certain rights and responsibilities depending on the software license you purchased or subscribed to as more fully described below (collectively the "Software"). By clicking "ACCEPT", you indicate that you have read and understood and assent to be bound by the terms of this Agreement. If you do not agree to the terms of this Agreement, you are not granted any rights whatsoever in the Software, and you will not be able to access or use the Software or Services.
	</p>
	<p class="marTop10px"><strong class="blueTxt">1. License Grant and Restrictions.</strong></p>
	<p class="marTop10px">
		Triesten Technologies LLC. ("Triesten Technologies LLC", "us", "we", "our") grants you ("you", "your" or "user") means the person using the Software in any way, the following rights provided that you comply with all of the terms and conditions of this Agreement.
	</p>
	<p class="marTop10px">
		(a) SimpleTruckTax. You may use: (i) SimpleTruckTax - software solely to prepare Business tax return for your Business, and after proper registration and any applicable payment, to file electronically. (ii) If you are Tax preparer and qualified by the IRS, you may use SimpleTruckTax software for your client's Business on a professional or commercial basis. You are not licensed or permitted under this Agreement to do any of the following: (i) attempt to access any other Triesten Technologies LLC systems, programs or data that are not made available for public use; (ii) prepare tax returns, schedules or worksheets on a professional or commercial basis (i.e., for a preparer's or other fee) unless as stated above in 1 (a); (iii) copy, reproduce, republish, upload, post, transmit, resell or distribute in any way the material from the Software sites; (iv) work around any technical limitations in the Software, use any tool to enable features or functionalities that are otherwise disabled in the Software, or decompile, disassemble, or otherwise reverse engineer the Software except as otherwise permitted by applicable law, (v) use the Software for any commercial purpose (vi) perform or attempt to perform any actions that would interfere with the proper working of the Software or Services, prevent access to or the use of the Software or Services by Triesten Technologies LLC's other licensees or customers, or impose an unreasonable or disproportionately large load on Triesten Technologies LLC infrastructure; or (vii) otherwise use the Software except as expressly allowed under this Section1.
	</p>
	<p class="marTop10px">
		(b) If you obtained a license for the free version of the SimpleTruckTax software, there may be additional fees and limitations on your use of the features and functionality, stated within the SimpleTruckTax software. 
	</p>
	<p class="marTop10px">
		(c) You must indemnify and defend Triesten Technologies LLC against any claims or lawsuits, including attorneys' fees that arise from or result from the use of the Software on a professional or commercial basis.
	</p>
	<p class="marTop10px">
		In addition to the SimpleTruckTax software, the term "Software" includes any other programs, tools, internet-based services, components and any "updates" (for example, Software maintenance, service information, help content, bug fixes, or maintenance releases etc.) of the Software that Triesten Technologies LLC provides or makes available to you.
	</p>
	<p class="marTop10px"><strong class="blueTxt">2. Reservation of Rights and Ownership.</strong></p>
	<p class="marTop10px">
		The Software is licensed not sold, and Triesten Technologies LLC reserves all rights not expressly granted to you in this Agreement. The Software is protected by copyright, trade secret and other intellectual property laws. Triesten Technologies LLC and its licensors own the title, copyright, and other intellectual property rights in the Software. This Agreement does not grant you any rights to trademarks or service marks of Triesten Technologies LLC.
	</p>
	<p class="marTop10px"><strong class="blueTxt">3. SimpleTruckTax Accurate Calculations Guarantee.</strong></p>
	<p class="marTop10px">
		Triesten Technologies LLC diligently works to ensure the accuracy of the calculations on every form prepared using SimpleTruckTax, tax preparation software.
	</p>
	<p class="marTop10px">
		(i) If you are a registered user and you pay an IRS or state penalty and/or interest solely because of a calculation error on a form prepared for you using Corporate Taxes Online, and not as a result of, among other things, your failure to enter all required information accurately, willful or fraudulent omission or inclusion of information on your tax return, misclassification of information on the tax return, or failure to file an amended return to avoid or reduce an applicable penalty/interest after Triesten Technologies LLC announced updates or corrections to the SimpleTruckTax Online software in time for you to file an amended return, then Triesten Technologies LLC will pay you in the amount of the IRS or state penalty and/or interest paid by you to the IRS or state. In this regard, you are responsible for keeping Triesten Technologies LLC apprised promptly of any change in your email address, mailing address and/or phone number so that you can be notified of such updates or corrections. You are responsible for paying any additional tax liability you may owe and providing any other information Triesten Technologies LLC reasonably requests. A "registered user" is a user from whom Triesten Technologies LLC has received the information necessary to permit such person to print or electronically file a tax return prepared using the SimpleTruckTax Online software and who complies with the terms and conditions of this Agreement.
	</p>
	<p class="marTop10px">
		(ii) If you believe such a calculation error occurred, you must notify Triesten Technologies LLC as soon as you learn of the mistake (and in no event later than 30 days after the penalty or interest is assessed) at http://www. SimpleTruckTax.com/ContactUs, or by mail at Triesten Technologies LLC Inc.
	</p>
	<p class="marTop10px">
		<b>Simple Truck Tax - Triesten Technologies, LLC</b> <br/>
		Westmoor Technology Park, 10955 Westmoor Drive,<br/>
		Suite# 4100, 4th Floor, Westminster,<br/>
		COLORADO - 80021,<br/>
		USA.<br/>
		Phone : +1 303 379 1280 / 916 719 6150<br/>
		Fax : +1 303 379 2100<br/>
		Email : <a href="mailto:info@simpletrucktax.com" alt="Email Us" title="Email Us" class="blueTxt">info@simpletrucktax.com</a>
	</p>
	<p class="marTop10px">
		Triesten Technologies LLC will then contact you promptly to resolve the issue. To resolve your matter, Triesten Technologies LLC may require your SimpleTruckTax tax data file and other supporting information such as a copy of the IRS/state notice, evidence of payment of the specified penalty and/or interest, and a copy of your printed tax return.
	</p>
	<p class="marTop10px"><strong class="blueTxt">4. Triesten Technologies LLC Services and Third Party Services (together "Services").</strong></p>
	<p class="marTop10px"><strong>A. Triesten Technologies LLC Services.</strong></p>
	<p class="marTop10px">
		<u>Electronic Filing Services.</u><br/><br/>
		(i) If you choose to file your return electronically, the tax return will be forwarded to Triesten Technologies LLC's Electronic Filing Servers, where it will be converted to and stored in a standardized format, and then transmitted to the applicable federal and/or state taxing authority. You are responsible for verifying the status of your return to confirm that it has been received and accepted by the applicable taxing authority and, if necessary, for filing it manually in the event that the taxing authority rejects your electronically filed return (e.g., Business Name and EIN don't match). You agree to review your tax return for indications of obvious errors before electronically filing it. To the extent required by applicable law and regulation, Triesten Technologies LLC stores and maintains information that you provide to Triesten Technologies LLC. Triesten Technologies LLC is not required or obligated to provide you with copies of this information. If you require a copy your tax return, you must contact the IRS.
	</p>
	<p class="marTop10px">
		(ii) Although Business Tax filing is a year around process, time to time the Internal Revenue Service ("IRS") will not accept the returns due to various reasons including but not limited to maintenance of their computer systems. SimpleTruckTax may be operational during this time for you to prepare your tax returns, but if you want to file it electronically, you will need to sign back in to SimpleTruckTax Online when the downtime is over to complete the electronic filing process. We take every measure to keep a log of the downtime on our website, but it is your responsibility to sign back and file the returns electronically. The IRS requires Triesten Technologies LLC to notify it, in connection with the electronic filing of your tax return, of the Internet Protocol ("IP") address of the computer from which the return originated and whether the email address of the person electronically filing the return has been collected. By using this Service to prepare and submit your tax return, you consent to the disclosure to the IRS and any other tax or revenue authority of all information relating to your use of the Electronic Filing Services.
	</p>
	<p class="marTop10px">
		<u>Help and Support.</u> Triesten Technologies LLC may use a variety of methods (e.g., in-product, Internet, e-mail, chat, fax and phone) to provide technical support and customer service in connection with Software and Triesten Technologies LLC Services. The terms and conditions governing the offering of this support, which may require the payment of an additional fee, are subject to change as announced by Triesten Technologies LLC from time to time. Consult the SimpleTruckTax Help and Support web site (currently, http://www. SimpleTruckTax.com/support) for the most up-to-date information relating to this support and any associated charges.
	</p>
	<p class="marTop10px">
		<u>Feedback.</u> Triesten Technologies LLC may provide you with a mechanism to provide feedback, suggestions and ideas, if you choose, about its online products and services ("Feedback"). You agree that you are free to provide your opinion or suggestion to us. You agree that Triesten Technologies LLC may, in its sole discretion, use the Feedback you provide to Triesten Technologies LLC in any way, including in future modifications of the Software, multimedia works and/or advertising and promotional materials relating thereto. You hereby grant Triesten Technologies LLC a perpetual, worldwide, fully transferable, irrevocable, royalty free license to use, reproduce, modify, create derivative works from, distribute and display the Feedback in any manner for any purpose.
	</p>
	<p class="marTop10px"><strong>B. Third Party Websites</strong></p>
	<p class="marTop10px">
		The Software and Services may contain or reference links to websites operated by third parties ("Third Party Websites"). These links are provided as a convenience only. Such Third Party Websites are not under the control of Triesten Technologies LLC. Triesten Technologies LLC is not responsible for the content of any Third Party Website or any link contained in a Third Party Website. Triesten Technologies LLC does not review, approve, monitor endorse, warrant, or make any representations with respect to Third Party Websites, and the inclusion of any link in the Software or Services is not and does not imply an affiliation, sponsorship, endorsement, approval, investigation, verification or monitoring by Triesten Technologies LLC or its Suppliers (defined below) of any information contained in any Third Party Website. In no event will Triesten Technologies LLC or its Suppliers be responsible for the information contained in such Third Party Website or for your use of or inability to use such website. Access to any Third Party Website is at your own risk, and you acknowledge and understand that linked Third Party Websites may contain terms and privacy policies that are different from those of Triesten Technologies LLC and its Suppliers. Neither Triesten Technologies LLC nor its Suppliers are responsible for such provisions, and expressly disclaim any liability for them.
		You are responsible for providing, at your expense, any access to the Internet and any required equipment. Further, Triesten Technologies LLC may at any time change or discontinue any aspect, availability or feature of the Services.
	</p>
	<p class="marTop10px"><strong>C. Payment &amp; Collection.</strong></p>
	<p class="marTop10px">
		In the event you owe Triesten Technologies LLC any amounts related to your licensing of SimpleTruckTax and/or Services, Triesten Technologies LLC reserves the right to seek collection of any amount unpaid. There will no refunds once the Tax Return is transmitted to IRS. SimpleTruckTax is not responsible for the errors and omissions you make when entering the data.
	</p>
	<p class="marTop10px"><strong class="blueTxt">5. User ID and Password Security.</strong></p>
	<p class="marTop10px">
		You are the only person authorized to use your user ID and password and for maintaining the confidentiality of your user ID and password. You shall not permit or allow other persons to have access to or use your user ID and password, except if you choose to provide that information to Triesten Technologies LLC's authorized technical support personnel to assist you. You are responsible for the use of the Software under your user ID. Triesten Technologies LLC will not disclose your password if you lose or forget it. If you have not electronically filed or printed your tax return, you must create a user ID and password in order for you to access your tax return data at a later date. You must remember your user ID and password to electronically transfer your tax return information into next tax return if you choose to do so.
	</p>
	<p class="marTop10px">
		You should confirm that the pricing for your use of the Software and/or Services has not changed, particularly if some time has passed between the date you start your tax return and the date you finish and are ready to file or print and pay for it. 
	</p>
	<p class="marTop10px"><strong class="blueTxt">6. Privacy of Personal and Tax Return Information.</strong></p>
	<p class="marTop10px">
		At Triesten Technologies LLC we place the highest importance on respecting and protecting the privacy of our customers. Our most important asset is our relationship with you. We want you to feel comfortable and confident when using our products and services and with entrusting your tax return information to us. 
	</p>
	<p class="marTop10px"><strong class="blueTxt">7. DISCLAIMER OF WARRANTIES.</strong></p>
	<p class="marTop10px"><strong>A. Triesten Technologies LLC Services.</strong></p>
	<p class="marTop10px">
		EXCEPT AS EXPRESSLY IN ABOVE, THE SOFTWARE AND SERVICES ARE PROVIDED "AS-IS" AND, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Triesten Technologies LLC, ITS AFFILIATES, LICENSORS, PARTICIPATING FINANCIAL INSTITUTIONS, THIRD-PARTY CONTENT OR SERVICE PROVIDERS, RETAILERS, DISTRIBUTORS, DEALERS AND SUPPLIERS (COLLECTIVELY, "SUPPLIERS") DISCLAIM ALL GUARANTEES AND WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SOFTWARE OR SERVICES, INCLUDING ANY WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, MERCHANTABILITY, QUALITY, TIMELINESS, AND NON-INFRINGEMENT. Triesten Technologies LLC DOES NOT WARRANT THAT SOFTWARE OR SERVICES ARE SECURE, FREE FROM BUGS, VIRUSES, INTERRUPTION, ERRORS, OR OTHER PROGRAM LIMITATIONS. SOME STATES DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. IN THAT EVENT, ANY IMPLIED WARRANTIES ARE LIMITED IN DURATION TO 60 DAYS FROM THE DATE OF PURCHASE OF SOFTWARE OR SERVICES, AS APPLICABLE. HOWEVER, SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. THIS WARRANTY GIVES YOU SPECIFIC LEGAL RIGHTS, AND YOU MAY HAVE OTHER RIGHTS THAT VARY FROM STATE TO STATE.
		All warranties or guarantees given or made by Triesten Technologies LLC with respect to Software or the Services (1) are solely for the benefit of you as the registered user of the Software and are not transferable, and (2) shall be null and void if you breach any term or condition of this Agreement.
	</p>
	<p class="marTop10px"><strong class="blueTxt">8. LIMITATION OF LIABILITY AND DAMAGES.</strong></p>
	<p class="marTop10px">
		YOU UNDERSTAND THAT Triesten Technologies LLC WILL NOT AUDIT OR OTHERWISE VERIFY ANY INFORMATION YOU PROVIDE, AND IS NOT RESPONSIBLE FOR DISALLOWED DEDUCTIONS OR CREDITS. FURTHER, Triesten Technologies LLC SHALL NOT BE RESPONSIBLE FOR ADDITIONAL TAXES, PENALTIES AND INTEREST THAT ARE ASSESSED AS THE RESULT OF INCORRECT, INCOMPLETE OR MISLEADING INFORMATION THAT YOU HAVE GIVEN TO Triesten Technologies LLC IN CONNECTION WITH ITS PREPARATION OF YOUR TAX RETURNS USING THE SERVICES.
		EXCEPT FOR THE REIMBURSEMENT FOR CALCULATION ERRORS DESCRIBED IN SECTION 3 AND 4 A., THE ENTIRE CUMULATIVE LIABILITY OF Triesten Technologies LLC AND ITS SUPPLIERS FOR ANY REASON ARISING FROM OR RELATING TO THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT PAID BY YOU FOR THE SOFTWARE OR SERVICES, AS APPLICABLE, TO Triesten Technologies LLC OR ITS AUTHORIZED RESELLER.
	</p>
	<p class="marTop10px">
		TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, Triesten Technologies LLC AND ITS SUPPLIERS ARE NOT LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL DAMAGES OR FOR DAMAGES RELATING TO LOSS OF BUSINESS, TELECOMMUNICATION FAILURES, LOSS, CORRUPTION, SECURITY OR THEFT OF DATA, VIRUSES, SPYWARE, LOSS OF PROFITS OR INVESTMENT, TAX POSITIONS TAKEN BY YOU, INABILITY TO FILE YOUR RETURN, DELAY IN PREPARING YOUR TAX RETURN, INCORRECT OR INCOMPLETE INFORMATION PROVIDED TO Triesten Technologies LLC, ANY ACCESS TO, OR USE OF, YOUR PASSWORD AND USER ID BY AN UNAUTHORIZED PERSON, OR THE LIKE, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, PRODUCT LIABILITY OR OTHERWISE, EVEN IF Triesten Technologies LLC OR ITS SUPPLIERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE. IN NO EVENT WILL Triesten Technologies LLC BE LIABLE FOR ANY LOSS, COST, LIABLITY OR DAMAGE INCURRED AS A RESULT OF YOUR RECEIPT OF OR PARTICIPATION IN THIRD PARTY SERVICES OR THIRD PARTY WEBSITES. IN NO EVENT DOES Triesten Technologies LLC ASSUME ANY LIABILITY TO ANY PARTY OTHER THAN YOU ARISING OUT OF YOUR USE OR INABILITY TO USE THE SOFTWARE OR SERVICES. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN Triesten Technologies LLC AND YOU. Triesten Technologies LLC WOULD NOT BE ABLE TO HAVE PROVIDED SimpleTruckTax OR SERVICES WITHOUT SUCH LIMITATIONS.
	</p>
	<p class="marTop10px"><strong class="blueTxt">9. Consent to Conduct Business Electronically ("Consent").</strong></p>
	<p class="marTop10px">
		(a) Consent to Electronic Communications. Triesten Technologies LLC may be required by law to send "Communications" to you that may pertain to the Software, the use of information you may submit to Triesten Technologies LLC and the Services you choose. Additionally, certain of the Third Party Services you choose, may require Communications with the third parties who administer these programs. You agree that Triesten Technologies LLC, on behalf of itself and others who administer such Services (as applicable), may send Communications to you by email and/or may make Communications available to you by posting them at one or more of our sponsored websites, such as http://www. SimpleTruckTax.com. You Consent to receive these Communications electronically. The term "Communications" means any notice, record, agreement, or other type of information that is made available to you or received from you in connection with the Software, the Services, or your tax refund. (b) Consenting to Do Business Electronically. The decision whether to do business electronically is yours, and you should consider whether you have the required hardware and software capabilities described below. Your consent to do business electronically, and our agreement to do so, applies to this Agreement, the Software and any applicable Services. (c) Hardware and Software Requirements. In order to access and retain an electronic record of Communications, you will need: a computer, a monitor, a connection to an Internet service provider, an Internet browser software that supports 128-bit encryption, and an e-mail address. By selecting the "I accept and agree to the terms of the License Agreement" button, you are confirming to us that you have the means to access, and to print or download, Communications. We do not provide ISP services. You must have your own Internet service provider.(d) Withdrawal of Consent. If you later decide that you do not want to receive future Communications electronically, write to us at SimpleTruckTax Customer Service, support@ SimpleTruckTax.com. If you withdraw your consent to receive Communications electronically, we may terminate your use of Tax Advice and one or more of the Services. (e) Changes to Your Email Address. You agree to notify us promptly of any change in your email address. You can do so by logging on to http://www. SimpleTruckTax.com and following the instructions to submit a comment to Triesten Technologies LLC (please include both your old and new email address). (f) Printing. You may print this document by clicking on the "Print License Agreement" button.
	</p>
	<p class="marTop10px"><strong class="blueTxt">10. Miscellaneous.</strong></p>
	<p class="marTop10px">
		This Agreement (and any additional terms and conditions with which Triesten Technologies LLC amends or supplements this Agreement), is a complete statement of the agreement between you and Triesten Technologies LLC, and sets forth the entire liability of Triesten Technologies LLC and its Suppliers and your exclusive remedy with respect to the Software and Services and their use. You agree that Triesten Technologies LLC is not acting as your agent or fiduciary in connection with your use of the Software or any Services. The Suppliers, agents, employees, distributors, and dealers of Triesten Technologies LLC are not authorized to make any additional representations, commitments, or warranties binding on Triesten Technologies LLC. Any waiver of the terms herein by Triesten Technologies LLC must be in a writing signed by an authorized officer of Triesten Technologies LLC and expressly referencing the applicable provisions of this Agreement. Triesten Technologies LLC shall be not be liable for any default or delay in the performance of its obligations under this Agreement to the extent its performance is delayed or prevented due to causes beyond its reasonable control, such as acts of God, natural disasters, terrorist acts, war or other hostilities, labor disputes, civil disturbances, the actions or omissions of third parties, electrical or communication system failures, or governmental action. If any provision of this Agreement is invalid or unenforceable under applicable law, then it shall be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law, and the remaining provisions will continue in full force and effect. 
	</p>
	<p class="marTop10px">
		SimpleTruckTax collects contact information for promotional, marketing, training, and customer support purposes. This information is not shared, sold, or distributed to third parties or other companies. Triesten Technologies LLC may contact customers with special promotional offers or informative reminders at different points during the tax season. Customers have the option to unsubscribe from any email marketing campaign or promotional offer at any time.
	</p>
	<p class="marTop10px"><strong class="blueTxt">11. Termination and Amendment.</strong></p>
	<p class="marTop10px">
		(a) Termination. Your rights under this Agreement may be terminated by Triesten Technologies LLC immediately and without notice if you fail to comply with any term or condition of this Agreement or no longer consent to electronic Communications. Upon such termination, you must immediately cease using the Software, Tax Advice and Services. Any termination of this Agreement shall not affect Triesten Technologies LLC's rights hereunder.
	</p>
	<p class="marTop10px">
		(b) Amendment. Triesten Technologies LLC shall have the right to change or add to the terms of its Agreement at any time, and to change, delete, discontinue, or impose conditions on any feature or aspect of Software, Tax Advice and Services (including internet based services, pricing, technical support options, and other product-related policies) upon notice by any means Triesten Technologies LLC determines in its discretion to be reasonable, including posting information concerning any such change, addition, deletion, discontinuance or conditions in Software or on any Triesten Technologies LLC sponsored web site, including <a href="http://www.simpletrucktax.com" alt="www.SimpleTruckTax.com" title="www.SimpleTruckTax.com" class="blueTxt">www.SimpleTruckTax.com</a> Any use of the Software by you after Triesten Technologies LLC's publication of any such changes shall constitute your acceptance of this Agreement as modified.
	</p>
	<p class="marTop10px"><strong class="blueTxt">12. Questions.</strong></p>
	<p class="marTop10px">
		You can contact Triesten Technologies LLC, Inc. by mail at Customer Support, Triesten Technologies LLC, Inc., ADDRESS, if you have a question or concern about any product or service we sell over the Internet. 
	</p>
	<p class="marTop10px">
		<b>Simple Truck Tax - Triesten Technologies, LLC</b> <br/>
		Westmoor Technology Park, 10955 Westmoor Drive,<br/>
		Suite# 4100, 4th Floor, Westminster,<br/>
		COLORADO - 80021,<br/>
		USA.<br/>
		Phone : +1 303 379 1280 / 916 719 6150<br/>
		Fax : +1 303 379 2100<br/>
		Email : <a href="mailto:info@simpletrucktax.com" alt="Email Us" title="Email Us" class="blueTxt">info@simpletrucktax.com</a>
	</p>
</div>
<!---------maincontainer section ends here------------>	
<?php include_once 'footer.php';?>
